DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS producer;
DROP TABLE IF EXISTS beat;
DROP TABLE IF EXISTS payment;

CREATE TABLE client(
	c_id BINARY(16) PRIMARY KEY UNIQUE,
	email VARCHAR(36) UNIQUE,
	phone_number INT(20) UNIQUE,
	name VARCHAR(36)
);
